spring.application.name=pharma
spring.data.mongodb.uri=mongodb://localhost:27017/pharma
server.port=8080
jwt.secret=medistocksecretkeymedistocksecretkey
<<<<<<< HEAD

jwt.expiration=86400000

=======
jwt.expiration=86400000
>>>>>>> 78d55e440fe885e238d85b4a6347a4c1577c5756
